function initAce(callback){
	addScript({src:'lib/ace-min-noconflict/ace.js'},function(){
		var T=ace.edit('eCode'),s=T.getSession();
		T.setTheme('ace/theme/github');
		T.setValueAndFocus=function(v){
			T.setValue(v);T.focus();T.gotoLine(0,0);
		};
		s.setMode('ace/mode/javascript');
		s.on('change',E.markDirty);
		s.setUseSoftTabs(false);
		s.setUseWrapMode(true);
		s.setUseWorker(true);
		T.clearHistory=s.getUndoManager().reset;
		T.commands.addCommand({
			name:'Save',
			bindKey:{win:'Ctrl-S',mac:'Command-S'},
			exec:eSave,
			readOnly:false,
		});
		T.commands.addCommand({
			name:'Exit',
			bindKey:{win:'Esc'},
			exec:E.close,
			readOnly:true,
		});
		callback(T);
	});
}

function initCodeMirror(callback){
	addCSS([
		{href:'lib/CodeMirror/lib/codemirror.css'},
	]);
	addScript({src:'lib/CodeMirror/lib/codemirror.js'},function(){
		addScript([
			{src:'lib/CodeMirror/mode/javascript/javascript.js'},
			{src:'lib/CodeMirror/addon/comment/continuecomment.js'},
			{src:'lib/CodeMirror/addon/edit/matchbrackets.js'},
			{src:'lib/CodeMirror/addon/search/match-highlighter.js'},
			{src:'lib/CodeMirror/addon/search/search.js'},
			{src:'lib/CodeMirror/addon/search/searchcursor.js'},
			{src:'lib/CodeMirror/addon/selection/active-line.js'},
		],function(){
			CodeMirror.keyMap.vm={
				'Esc':'close',
				'Ctrl-S':'save',
				'fallthrough':'default'
			};
			CodeMirror.commands.save=eSave;
			CodeMirror.commands.close=E.close;
			var T=CodeMirror($('eCode'),{
				lineNumbers:true,
				matchBrackets:true,
				mode:'text/typescript',
				lineWrapping:true,
				indentUnit:4,
				indentWithTabs:true,
				extraKeys:{"Enter":"newlineAndIndentContinueComment"},
				keyMap:'vm',
				styleActiveLine:true,
			});
			T.clearHistory=function(){T.getDoc().clearHistory();};
			T.setValueAndFocus=function(v){T.setValue(v);T.focus();};
			T.on('change',E.markDirty);
			T.getWrapperElement().setAttribute('style','position:absolute;height:100%;width:100%;');
			callback(T);
		});
	});
}
