allowBuilds:
  sharp: false
  unrs-resolver: false
  vueleton: false

minimumReleaseAgeExclude:
  - postcss@7.0.36 || 8.4.31 || 8.5.10 || 8.5.12 || 8.5.18 || 8.5.23
  - braces@3.0.3
  - micromatch@4.0.8

overrides:
  braces@<3.0.3: ^3.0.3
  micromatch@<4.0.8: ^4.0.8
  postcss@<7.0.36: ^7.0.36
  postcss@<8.4.31: ^8.4.31
  postcss@<8.5.10: ^8.5.10
  postcss@<=8.5.11: ^8.5.12
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
