allowBuilds:
  sharp: false
  unrs-resolver: false
  vueleton: false

minimumReleaseAgeExclude:
  - '@usync/drive@0.3.1'
  - '@usync/oauth2@0.1.8'
  - '@usync/util@0.1.0'

overrides:
  braces@<3.0.3: ^3.0.3
  micromatch@<4.0.8: ^4.0.8
  nanoid@<3.3.18: ^3.3.18
  nanoid@>=4.0.0 <5.1.16: ^5.1.16
  postcss@<7.0.36: ^7.0.36
  postcss@<8.4.31: ^8.4.31
  postcss@<8.5.10: ^8.5.10
  postcss@<=8.5.11: ^8.5.12
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
