import test from 'tape';
import CodeMirror from 'codemirror';
import 'codemirror/addon/runmode/runmode-standalone';
import '#/common/ui/codemirror-js-mixed/javascript-mixed';
import fs from 'fs';
import path from 'path';


/**
 * A sanity / regression test for javascript-mixed mode, comparing
 * the text in code-source.txt agains the expected tokens
 * The tokens format can be generated by opening runmode.html, an utitlity to
 * tokenize any codes. It is also useful to visualize the results in case regression happens.
 */
test('codemirror javascript-mixed regression', (t) => {
  const code = fs.readFileSync(path.join(__dirname, 'code-source.txt'), 'utf8');
  const expected = fs.readFileSync(path.join(__dirname, 'code-tokens.txt'), 'utf8');
  let tokenRes = '';
  const EOF_HINT = '// EOF'; // used to signify the end of tokenization
  CodeMirror.runMode(`${code}\n${EOF_HINT}`, 'javascript-mixed',
    (text, style) => {
      if (text !== EOF_HINT) {
        tokenRes += `${`${style} | ${text}`.trimRight()}\n`;
      } else {
        t.equal(tokenRes, expected);
        t.end();
      }
    });
});
