const fs = require('fs');
const yaml = require('js-yaml');
const childProcess = require('child_process');

const [, ownPath, type] = process.argv;
const SRC = 'src/_locales/en/messages.yml';
const DST = 'src/types.generated.d.ts';

const srcText = fs.readFileSync(SRC, 'utf8');
const dstText = fs.readFileSync(DST, 'utf8');

const dstText2 = `\
// DO NOT EDIT!
// This file is auto-generated by ${
  ownPath.slice(process.cwd().length + 1).replace(/\\/g, '/')
}
declare type LocaleMessageId =
  '${Object.keys(yaml.load(srcText)).join("' |\n  '")}';
`;

if (dstText2 !== dstText) {
  fs.writeFileSync(DST, dstText2, 'utf8');
  childProcess.execSync(`git add "${DST}"`
    + (type ? ' && git commit -m "chore: regenerate types"' : ''));
}
